name = "bluetap"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[vars]
ALLOWED_ORIGIN = "*"
ALLOW_DEV_AUTH = "false"
AUTH_MAX_AGE_SECONDS = "86400"
BLUEX_JETTON_MASTER = "EQCUcgi1T0zSOvRIIM4ucj83GI2xqTxrLhaAlwaH8tOw9oTJ"
BOT_USERNAME = "bluecoinxbot"

[[d1_databases]]
binding = "DB"
database_name = "bluetap"
database_id = "fe5b6d30-7f97-404a-a846-7f2a9657715e"
migrations_dir = "migrations"

[assets]
directory = "../web/dist"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = ["/api/*", "/health", "/telegram/*"]
